export const WEAPON_NAMES = {
  ROCK: 'WEAPON_ROCK',
  PAPER: 'WEAPON_PAPER',
  SCISSOR: 'WEAPON_SCISSOR',
}

export const WEAPON_WINNER = {
  [WEAPON_NAMES.ROCK]: WEAPON_NAMES.PAPER,
  [WEAPON_NAMES.PAPER]: WEAPON_NAMES.SCISSOR,
  [WEAPON_NAMES.SCISSOR]: WEAPON_NAMES.ROCK,
}